In [1]:
# 반복문
# for 반복문
for i in range(1, 11):              # 1부터 11-1까지의 범위를 i가 순회할 때마다
    print('hello!')                 # hello! 출력

# -->변수 : i, 범위 : range(1:11)->1~10
# 들여쓰기된 부분까지만 반복문 실행

# for 변수 in 범위:
#     반복코드1 --|
#     반복코드2 -----> 코드블럭
#     반복코드3 --|
    
for i in range(1, 6):
    print(123)
    print(456)
    print(789)

hello!
hello!
hello!
hello!
hello!
hello!
hello!
hello!
hello!
hello!


In [2]:
for i in range(1, 6):
    print(123)
print(456)
    print(789)              # indentation error : 들여쓰기 에러. print(456)을 들여써서 이 줄을 코드블럭에 포함시키던지, 들여쓰기를 지워야함

IndentationError: unexpected indent (3331321933.py, line 4)

In [ ]:
# range함수
range(start, stop, step)        # start : 시작숫자(기본값 0) / stop : 멈출 숫자(1크게 입력) / step : 범위 내에서 step값만큼 증가(기본값 1)

In [23]:
# 실습
# 25 이하의 자연수에서, 2의 배수만 출력
for i in range(1, 13):              # for i in range(2, 26, 2):
    print(i * 2)


2
4
6
8
10
12
14
16
18
20
22
24


In [24]:
# -8 ~ -13범위의 정수 출력
for i in range(-8, -14, -1):
    print(i)


-8
-9
-10
-11
-12
-13


In [25]:
# 30미만의 3의 배수 출력
for i in range(1, 10):          # for i in range(3, 30, 3):
    print(i * 3)


3
6
9
12
15
18
21
24
27


In [26]:
# 0.1, 0.2, 0.3, 0.4, 0.5순서로 숫자 출력
for i in range(1, 6):
    print(round(i * 0.1, 1))

0.1
0.2
0.3
0.4
0.5


In [1]:
num = int(input())
for i in range(2, num + 1, 2):
    print(i, end=" ")

27
2 4 6 8 10 12 14 16 18 20 22 24 26 

In [7]:
# while반복문
num = int(input())
i = 2
while i <= num:
    print(i)
    i += 2

16
2
4
6
8
10
12
14
16


In [9]:
for i in range(1, 11):
    print(i)
    continue        # 특정 상황에서만 실행되는 구조를 만들때 사용
    print('---')

1
2
3
4
5
6
7
8
9
10


In [8]:
for i in range(1, 11):
    print(i)
    break
    print('---')

1


In [10]:
for i in range(1, 11):
    print(i)
    pass        # 반복문에서 구조를 임시로 만들어줄 때 주로 사용
    print('---')

1
---
2
---
3
---
4
---
5
---
6
---
7
---
8
---
9
---
10
---


In [11]:
# 다중 루프 실습
list1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for i in range(3):
    for j in range(3):
        print(list1[i][j], end = " ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [33]:
for i in list1:
    for j in i:
        print(j, end = " ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [12]:
for i in range(3):
    for j in range(3):
        print(list1[i][j], end = " ")

1 2 3 4 5 6 7 8 9 

In [16]:
i = 0
j = 0
while i<3:
    while j<3:
        print(list1[i][j], end = " ")
        j += 1
    print()
    j = 0
    i += 1

1 2 3 
4 5 6 
7 8 9 


In [17]:
i = 0
j = 0
while i<3:
    while j<3:
        print(list1[i][j], end = " ")
        j += 1
    j = 0
    i += 1

1 2 3 4 5 6 7 8 9 

In [26]:
for i in range(3):
    for j in range(3):
        print(" " * (list1[i][j] - 1), list1[i][j], sep = "")

1
 2
  3
   4
    5
     6
      7
       8
        9


In [27]:
i = 0
j = 0
while i<3:
    while j<3:
        print(" " * (list1[i][j] - 1), list1[i][j], sep = "")
        j += 1
    j = 0
    i += 1

1
 2
  3
   4
    5
     6
      7
       8
        9


In [28]:
for i in range(3):
    for j in range(3):
        print(list1[j][i], end = " ")
        
    print()

1 4 7 
2 5 8 
3 6 9 


In [30]:
for i in range(3):
    for j in range(3):
        print(list1[j][i], end = " ")

1 4 7 2 5 8 3 6 9 

In [29]:
i = 0
j = 0
while i<3:
    while j<3:
        print(list1[j][i], end = " ")
        j += 1
    print()
    j = 0
    i += 1

1 4 7 
2 5 8 
3 6 9 


In [31]:
i = 0
j = 0
while i<3:
    while j<3:
        print(list1[j][i], end = " ")
        j += 1
    j = 0
    i += 1

1 4 7 2 5 8 3 6 9 

In [35]:
# 조건문
x = 12345
if x == 123:
    print('x는 123입니다')
    
elif x == 1234:
    print('아닌데! x는 1234인데!')
else:
    print('너희 둘 다 아니야')

너희 둘 다 아니야


In [2]:
a = 99
b = 88

if a == 99 and b == 88:
    print('99와 88이 있어요')

99와 88이 있어요


In [3]:
if a == 88 or b == 88:
    print('둘 중에 무언가는 88이네요')

둘 중에 무언가는 88이네요


In [6]:
if not a == 100:
    print('100')

100


In [8]:
# 과제
num = int(input())                # 숫자 하나 입력받음
arr = []                          # 짝수만 저장해줄 빈 리스트 생성
for i in range(2, num + 1, 2):    # 입력받은 숫자까지의 범위 내에서 짝수만 반복
    arr.append(i)                 # 짝수만 arr에 저장
for i in arr:                     # 저장해둔 짝수 하나씩 반복
    temp = 1                      # 임시변수로 1(팩토리얼 계산용), 짝수가 바뀔 때마다 1로 다시 초기화
    for j in range(1, i + 1):     # 선택된 짝수까지의 숫자 하나씩 반복
        temp *= j                 # temp에 j값 곱해 팩토리얼 계산
    print(temp, end = " ")        # 결과 출력

6
2 24 720 

In [9]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr[2]

3

In [14]:
arr[1:5]

array([2, 3, 4, 5])

In [15]:
arr * 4

array([ 4,  8, 12, 16, 20])

In [16]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr3 = np.array([5, 6, 7])

In [17]:
arr2.dot(arr3)

array([ 38,  92, 146])

In [19]:
np.save('./f1.npy', arr)

In [ ]:
# npy파일 저장 및 불러오기
np.save('filename.npy', arr)    # numpy array 파일 확장자
arr = np.load('filename.npy')

# npz 파일 저장 및 불러오기
np.savez('filename.npz', A = arr)    # 어느 구역에 어떤 array를 저장할지 지정. np array의 압축파일 형식
arr = np.load('filename.npz')['A']

In [21]:
np.save('C:/Users/BIG03-01/Documents/빅데이터/f2.npy', arr)

In [22]:
np.load('./f1.npy')

array([1, 2, 3, 4, 5])

In [23]:
np.savez('./f1.npz', A = arr)

In [25]:
np.load('./f1.npz')['A']

array([1, 2, 3, 4, 5])

In [26]:
# pandas
import pandas as pd

In [29]:
df = pd.DataFrame([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [7, 4, 1, 8, 5]])
df

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0
2  7  4  1  8  5

In [30]:
df[1][1]

7

In [31]:
df[1][0]

2

In [32]:
df.loc[1]

0    6
1    7
2    8
3    9
4    0
Name: 1, dtype: int64

In [33]:
df.loc[1][0]

6

In [34]:
df.loc[1, 0]

6

In [35]:
df.loc[:, 1:3]    # 이름 기반 인덱싱. 1번 열과 3번 열의 사이 모든 열을 다 보이는 것. 마지막 컬럼이 없는 이름이면 끝까지 출력. 라벨 인덱싱 방법

1  2  3
0  2  3  4
1  7  8  9
2  4  1  8

In [36]:
df.iloc[:, 1:3]    # 숫자 기반 인덱싱. 위치 인덱싱 방법

1  2
0  2  3
1  7  8
2  4  1

In [51]:
df.index = ['ㄱ', 'ㄴ', 'ㄷ']
df.columns = ['a', 'b', 'c', 'd', 'e']

In [52]:
df

a  b  c  d  e
ㄱ  1  2  3  4  5
ㄴ  6  7  8  9  0
ㄷ  7  4  1  8  5

In [53]:
df.loc[:, 'c':'e']

c  d  e
ㄱ  3  4  5
ㄴ  8  9  0
ㄷ  1  8  5

In [54]:
df.iloc[:, 1:3]

b  c
ㄱ  2  3
ㄴ  7  8
ㄷ  4  1

In [55]:
df['b'] * 4

ㄱ     8
ㄴ    28
ㄷ    16
Name: b, dtype: int64

In [56]:
df * 4

a   b   c   d   e
ㄱ   4   8  12  16  20
ㄴ  24  28  32  36   0
ㄷ  28  16   4  32  20

In [57]:
df.to_csv('./df.csv')

In [58]:
pd.read_csv('./df.csv', index_col = 0, header = 2)

6  7  8  9  0
ㄴ               
ㄷ  7  4  1  8  5

In [59]:
df.to_csv('./df.csv', index = False)

In [60]:
pd.read_csv('./df.csv')

a  b  c  d  e
0  1  2  3  4  5
1  6  7  8  9  0
2  7  4  1  8  5

In [63]:
pd.read_csv('./안녕.csv', encoding = 'cp949')

가   나   다
0  1   2   3
1  4   5   6

In [64]:
df.to_excel('./df.xlsx')

In [65]:
pd.read_excel('./df.xlsx')

Unnamed: 0  a  b  c  d  e
0          ㄱ  1  2  3  4  5
1          ㄴ  6  7  8  9  0
2          ㄷ  7  4  1  8  5

In [66]:
pd.read_excel('./df.xlsx', comment = '#', index_col = 0)

a  b  c  d  e
ㄱ  1  2  3  4  5
ㄴ  6  7  8  9  0
ㄷ  7  4  1  8  5

In [67]:
# function
# def 함수이름(입력값):
#     함수에서 실행될 코드
#     return 리턴값


In [68]:
1+1    # return

2

In [69]:
print(1 + 1)    # print

2


In [70]:
def test(x):
    return x + 10

In [71]:
test(10)

20

In [72]:
def test2(x):
    return x + 10
    return x + 100

In [74]:
test2(10)    # 값 반환 후 함수 즉시 종료 --> 두번째 리턴은 실행되지 않음

20

In [75]:
def test3(x):
    if x % 2 == 0:
        return x + 10
    return x + 100

In [76]:
test3(11)

111

In [77]:
test3(10)

20

In [78]:
def test4(x):
    return x + 10, x + 100

In [79]:
test4(10)

(20, 110)

In [80]:
q, w = test4(10)

In [81]:
q

20

In [82]:
w

110

In [7]:
word = 'ljes=njak'
word[1:2]

'j'